const $=s=>document.querySelector(s);const app=document.getElementById('app');
const API='/api';
const qs=new URLSearchParams(location.search);let crewId=qs.get('crew')||'';let dropId=qs.get('drop')||'';
const pid=localStorage.addaPid||(`p_${crypto.randomUUID().replace(/-/g,'').slice(0,10)}`);localStorage.addaPid=pid;
let meName=localStorage.addaName||'';let crew=null,members=[],drops=[],screen='boot',tab='drops',selected=null,guestAnswer=null,pollTimer=null,chatTimer=null;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function esc(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1400)}
async function api(action,opts={}){const method=opts.method||'GET';const params=new URLSearchParams({action,...(opts.params||{})});const r=await fetch(`${API}?${params}`,{method,headers:{'content-type':'application/json'},body:method==='POST'?JSON.stringify(opts.body||{}):undefined});const j=await r.json();if(!r.ok)throw new Error(j.error||'Something went wrong');return j}
function track(event,meta={}){api('track',{method:'POST',body:{crewId:crewId||'anon',participantId:pid,event,meta}}).catch(()=>{})}
function shell(inner,nav=true){return `<section class="app"><div class="view">${inner}</div>${nav&&crew?navHtml():''}</section>`}
function top(title=crew?.name||'Adda',back=''){return `<div class="top">${back?`<button class="linkbtn" onclick="window._go('${back}')">←</button>`:`<div class="brand">Adda</div>`}<div class="grow"><h3>${esc(title)}</h3></div>${crew?`<span class="chip">${members.length} 👥</span>`:''}</div>`}
function navHtml(){return `<nav class="nav"><button class="${tab==='drops'?'active':''}" onclick="window._tab('drops')">⚡<br>Drops</button><button class="create" onclick="window._go('create')">+</button><button class="${tab==='chat'?'active':''}" onclick="window._tab('chat')">💬<br>Chat</button></nav>`}
window._go=s=>{screen=s;stopPolling();render()};window._tab=t=>{tab=t;screen='crew';stopPolling();render()};
function stopPolling(){clearInterval(pollTimer);clearInterval(chatTimer)}
function share(url,text='Join my Adda Crew 👀'){if(navigator.share)navigator.share({title:'Adda',text,url}).catch(()=>{});else navigator.clipboard?.writeText(url).then(()=>toast('Link copied'))}
window._shareCrew=()=>share(`${location.origin}/?crew=${crewId}`,`Join ${crew.name} on Adda 👀`);
window._shareDrop=(id)=>share(`${location.origin}/?crew=${crewId}&drop=${id}`,`Answer this Drop in ${crew.name} 👀`);

async function boot(){try{
 if(!crewId){screen='start';render();return}
 const c=await api('getCrew',{params:{crewId}});crew=c.crew;members=c.members;
 const member=members.find(m=>m.id===pid);
 if(!member){screen=dropId?'joinDrop':'join';render();return}
 meName=member.nickname;localStorage.addaName=meName;
 if(dropId){screen='drop';render();return}
 screen='crew';render();
}catch(e){screen='notfound';render(e.message)}}

function render(err=''){stopPolling();
 if(screen==='start')return renderStart();
 if(screen==='join')return renderJoin();
 if(screen==='joinDrop')return renderJoinDrop();
 if(screen==='notfound')return app.innerHTML=shell(`<div class="empty"><div><h1>Link not working</h1><p class="sub" style="margin-top:8px">${esc(err||'Ask your friend for a fresh link.')}</p><div class="sp18"></div><button class="btn dark" onclick="location.href='/'">Start Adda</button></div></div>`,false);
 if(screen==='crew')return tab==='chat'?renderChat():renderCrew();
 if(screen==='create')return renderCreate();
 if(screen==='drop')return renderDrop();
}
function renderStart(){app.innerHTML=shell(`<div class="hero"><span class="chip darkchip">YOUR PRIVATE CIRCLE</span><div class="sp18"></div><h1>Start with your people.</h1><p style="color:#cbc5d2;margin-top:9px">A Crew is your private friend group on Adda.</p></div><div class="sp18"></div><div class="card"><div class="field"><label>Your name</label><input id="name" maxlength="24" placeholder="e.g. Vijyant"></div><div class="sp12"></div><div class="field"><label>Name your Crew</label><input id="crewName" maxlength="42" placeholder="e.g. Weekend Crew"></div><div class="sp18"></div><button class="btn primary" onclick="window._createCrew()">Start Crew</button></div>`,false)}
window._createCrew=async()=>{const nickname=$('#name').value.trim(),name=$('#crewName').value.trim();if(!nickname||!name)return toast('Add your name and Crew name');try{const j=await api('createCrew',{method:'POST',body:{nickname,name,participantId:pid}});crewId=j.crew.id;crew=j.crew;meName=nickname;localStorage.addaName=nickname;history.replaceState({},'',`/?crew=${crewId}`);track('crew_created');await refreshCrew();screen='crew';render()}catch(e){toast(e.message)}};
function renderJoin(){app.innerHTML=shell(`${top(crew?.name||'Join Crew')}<div class="hero"><span class="chip darkchip">INVITE ONLY</span><div class="sp18"></div><h1>${esc(crew.name)}</h1><p style="color:#cbc5d2;margin-top:8px">${members.length} friends are here.</p></div><div class="sp18"></div><div class="card"><div class="field"><label>What should your Crew call you?</label><input id="joinName" maxlength="24" value="${esc(meName)}" placeholder="Your name"></div><div class="sp18"></div><button class="btn primary" onclick="window._joinCrew()">Join Crew</button></div>`,false)}
window._joinCrew=async()=>{const nickname=$('#joinName').value.trim();if(!nickname)return toast('Add your name');try{await api('joinCrew',{method:'POST',body:{crewId,nickname,participantId:pid}});meName=nickname;localStorage.addaName=nickname;track('crew_joined');await refreshCrew();screen=dropId?'drop':'crew';render()}catch(e){toast(e.message)}};
async function renderJoinDrop(){
  let j;try{j=await api('getDrop',{params:{crewId,dropId,participantId:pid}})}catch(e){screen='notfound';return render(e.message)}
  const d=j.drop;
  app.innerHTML=shell(`${top(crew?.name||'Adda')}<div class="tiny">${labelType(d.type).toUpperCase()}</div><h1 style="margin-top:5px">${esc(d.question)}</h1><div class="sp12"></div>${d.options.map(o=>`<button class="choice ${guestAnswer===o.id?'selected':''}" aria-pressed="${guestAnswer===o.id}" onclick="window._selectGuest('${o.id}')"><span>${esc(o.label)}</span></button>`).join('')}<div class="sp12"></div><div class="field"><label>Your name</label><input id="guestName" maxlength="24" value="${esc(meName)}" placeholder="What should friends call you?"></div><div class="sp18"></div><button class="btn primary" style="font-size:18px" onclick="window._answerAndJoin()" ${!guestAnswer?'disabled style="opacity:.45;font-size:18px"':''}>Answer →</button><p class="sub center" style="margin-top:9px">Answering adds you to ${esc(crew.name)}.</p>`,false)
}
window._selectGuest=id=>{guestAnswer=id;renderJoinDrop()};
window._answerAndJoin=async()=>{const nickname=$('#guestName')?.value.trim();if(!nickname)return toast('Add your name');if(!guestAnswer)return;try{await api('joinCrew',{method:'POST',body:{crewId,nickname,participantId:pid}});meName=nickname;localStorage.addaName=nickname;track('crew_joined_via_drop');await api('answerDrop',{method:'POST',body:{crewId,dropId,participantId:pid,answer:guestAnswer}});track('response_submitted');await refreshCrew();screen='drop';render()}catch(e){toast(e.message)}};
async function refreshCrew(){const c=await api('getCrew',{params:{crewId}});crew=c.crew;members=c.members}
async function refreshDrops(){const j=await api('listDrops',{params:{crewId,participantId:pid}});drops=j.drops}
async function renderCrew(){await refreshCrew();await refreshDrops();app.innerHTML=shell(`${top()}<div class="row between"><div><div class="tiny">YOUR CREW</div><h1>${esc(crew.name)}</h1></div><button class="chip" onclick="window._shareCrew()">Invite friends</button></div><div class="sp18"></div>${drops.length?drops.map(d=>`<button class="drop" style="width:100%;text-align:left" onclick="window._openDrop('${d.id}')"><div class="row between"><span class="chip">${labelType(d.type)}</span><span class="meta">${d.responseCount}/${d.threshold}</span></div><div class="q">${esc(d.question)}</div><div class="meta">${d.revealed?'Result ready ✨':d.myResponse?'Waiting for friends…':'Tap to answer'}</div></button>`).join(''):`<div class="empty"><div><div style="font-size:44px">⚡</div><h2 style="margin-top:8px">No Drops yet</h2><p class="sub" style="margin-top:6px">Create one, then share it. Friends join when they answer.</p><div class="sp18"></div><button class="btn primary" onclick="window._go('create')">Create first Drop</button></div></div>`}`);pollTimer=setInterval(()=>{if(screen==='crew'&&tab==='drops')renderCrew()},4500)}
window._openDrop=id=>{dropId=id;history.replaceState({},'',`/?crew=${crewId}&drop=${id}`);screen='drop';render()};
function labelType(t){return ({likely:'👀 Who’s most likely',either:'⚖️ This or That',vote:'🗳️ Vote',rate:'⭐ Rate'})[t]||'Drop'}

function renderCreate(){const type=selected?.type||(members.length<2?'either':'likely');app.innerHTML=shell(`${top('Create a Drop','crew')}<h1>One question. That’s it.</h1><p class="sub" style="margin-top:6px">Pick a format, type, send.</p><div class="sp12"></div><div class="formats">${[['likely','👀','Most likely'],['either','⚖️','This / That'],['vote','🗳️','Vote'],['rate','⭐','Rate']].map(x=>`<button class="format ${type===x[0]?'on':''} ${x[0]==='likely'&&members.length<2?'locked':''}" onclick="window._type('${x[0]}')"><span>${x[1]}</span>${x[2]}</button>`).join('')}</div>${members.length<2?'<p class="sub" style="margin-top:7px">Most Likely unlocks after one friend joins.</p>':''}<div class="sp12"></div><div class="card"><div class="field"><label>${questionLabel(type)}</label><textarea id="q" maxlength="120" placeholder="${placeholder(type)}">${esc(selected?.question||'')}</textarea></div>${extraFields(type)}<div class="sp12"></div><div class="field"><label>Show the result…</label><div class="segment"><button id="th3" class="on" onclick="window._threshold('count')">After 2 answers</button><button id="thAll" onclick="window._threshold('everyone')">When everyone answers</button></div></div><div class="sp18"></div><button class="btn primary" onclick="window._publish()">Create & share</button></div>`);window._thresholdMode='count'}
function questionLabel(t){return t==='rate'?'What should your Crew rate?':'What do you want to ask?'}function placeholder(t){return t==='likely'?"Who’s most likely to cancel the plan?":t==='either'?'Chai or coffee?':t==='vote'?'Where should we go this weekend?':'Rate our last hangout'}
function extraFields(t){if(t==='either')return `<div class="sp12"></div><div class="row"><div class="field grow"><label>Choice 1</label><input id="a" maxlength="40" placeholder="Chai"></div><div class="field grow"><label>Choice 2</label><input id="b" maxlength="40" placeholder="Coffee"></div></div>`;if(t==='vote')return `<div class="sp12"></div><div class="field"><label>Choices</label><input id="o1" maxlength="40" placeholder="Option 1"><input id="o2" maxlength="40" placeholder="Option 2"><input id="o3" maxlength="40" placeholder="Option 3 (optional)"></div>`;return ''}
window._type=t=>{if(t==='likely'&&members.length<2)return toast('Most Likely unlocks after one friend joins');selected={type:t,question:$('#q')?.value||''};renderCreate()};window._threshold=m=>{window._thresholdMode=m;$('#th3')?.classList.toggle('on',m==='count');$('#thAll')?.classList.toggle('on',m==='everyone')};
window._publish=async()=>{const type=selected?.type||'likely',question=$('#q').value.trim();const body={crewId,participantId:pid,type,question,thresholdMode:window._thresholdMode||'count',thresholdCount:2};if(type==='either'){body.optionA=$('#a').value;body.optionB=$('#b').value}if(type==='vote'){body.options=[$('#o1').value,$('#o2').value,$('#o3').value]};try{const j=await api('createDrop',{method:'POST',body});track('drop_created',{type});dropId=j.drop.id;history.replaceState({},'',`/?crew=${crewId}&drop=${dropId}`);screen='drop';render();setTimeout(()=>window._shareDrop(dropId),500)}catch(e){toast(e.message)}};

async function renderDrop(){await refreshCrew();let j;try{j=await api('getDrop',{params:{crewId,dropId,participantId:pid}})}catch(e){toast(e.message);return}const d=j.drop;selected=j.myResponse?.answer||selected;
 if(j.revealed&&!sessionStorage.getItem(`seen_${dropId}`)){sessionStorage.setItem(`seen_${dropId}`,'1');return revealCountdown(d,j)}
 if(j.revealed)return renderResult(d,j);
 if(j.myResponse)return renderWaiting(d,j);
 app.innerHTML=shell(`${top(crew.name,'crew')}<div class="tiny">${labelType(d.type).toUpperCase()}</div><h1 style="margin-top:5px">${esc(d.question)}</h1><p class="sub" style="margin-top:7px">${j.responsesCount}/${j.threshold} answered</p><div class="sp12"></div>${d.options.map(o=>`<button class="choice ${selected===o.id?'selected':''}" aria-pressed="${selected===o.id}" onclick="window._select('${o.id}')">${d.type==='rate'?'<span style="font-size:22px">⭐</span>':''}<span>${esc(o.label)}</span></button>`).join('')}<div class="sp12"></div><button class="btn primary" style="font-size:18px" onclick="window._submitAnswer()" ${!selected?'disabled style="opacity:.45;font-size:18px"':''}>Submit answer</button>`);pollTimer=setInterval(()=>{if(screen==='drop')renderDrop()},3500)}
window._select=id=>{selected=id;renderDrop()};window._submitAnswer=async()=>{if(!selected)return;try{await api('answerDrop',{method:'POST',body:{crewId,dropId,participantId:pid,answer:selected}});track('response_submitted');renderDrop()}catch(e){toast(e.message)}};
function renderWaiting(d,j){const left=Math.max(0,j.threshold-j.responsesCount);app.innerHTML=shell(`${top(crew.name,'crew')}<div class="hero center"><div style="font-size:44px">⏳</div><div class="sp12"></div><h1>Waiting for ${left} friend${left===1?'':'s'}</h1><p style="color:#cbc5d2;margin-top:8px">Your answer is locked.</p><div class="sp18"></div><div class="progress"><span style="width:${Math.min(100,j.responsesCount/j.threshold*100)}%"></span></div></div><div class="sp18"></div><button class="btn primary" onclick="window._shareDrop('${d.id}')">Share with friends</button><div class="sp12"></div><button class="btn ghost" onclick="window._tab('chat')">Open Crew chat</button>`);pollTimer=setInterval(()=>{if(screen==='drop')renderDrop()},2500)}
async function revealCountdown(d,j){if(reduced)return renderResult(d,j);for(let n=3;n>=1;n--){app.innerHTML=shell(`<div class="hero center" style="min-height:520px;display:grid;place-items:center"><div><div class="countdown">${n}</div><h2 style="margin-top:10px">Result ready</h2></div></div>`,false);await new Promise(r=>setTimeout(r,650))}renderResult(d,j)}
function renderResult(d,j){const byId=Object.fromEntries(d.options.map(o=>[o.id,o.label]));const top=j.result?.ranked?.[0];const pct=top?Math.round(top.count/j.result.total*100):0;app.innerHTML=shell(`${topbarResult()}<div class="hero center"><div style="font-size:44px">✨</div><div class="sp12"></div><div class="resultNum">${pct}%</div><h1>${esc(byId[top?.answer]||'Result')}</h1><p style="color:#cbc5d2;margin-top:8px">${esc(d.question)}</p></div><div class="sp18"></div>${j.result.ranked.map(r=>`<div class="card" style="margin-bottom:8px"><div class="row between"><b>${esc(byId[r.answer]||r.answer)}</b><span>${r.count}</span></div></div>`).join('')}<div class="sp12"></div><button class="btn primary" onclick="window._go('create')">Make the next Drop</button><div class="sp12"></div><button class="btn ghost" onclick="window._shareDrop('${d.id}')">Share Drop</button>`)}
function topbarResult(){return `<div class="top"><button class="linkbtn" onclick="window._go('crew')">←</button><div class="grow"><h3>${esc(crew.name)}</h3></div><span class="chip">Result</span></div>`}

function chatHtml(messages){return messages.length?messages.map(m=>`<div class="msg ${m.participantId===pid?'me':''}"><div class="who">${esc(m.nickname)}</div>${esc(m.text)}</div>`).join(''):`<div class="empty"><div><div style="font-size:40px">💬</div><h3>Start the chat</h3><p class="sub" style="margin-top:5px">Only your Crew can see this.</p></div></div>`}
async function refreshChatMessages(){try{const j=await api('chatList',{params:{crewId}});const box=$('#chat');if(!box)return;const nearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<80;box.innerHTML=chatHtml(j.messages);if(nearBottom)box.scrollTop=box.scrollHeight}catch{}}
async function renderChat(){await refreshCrew();const j=await api('chatList',{params:{crewId}});app.innerHTML=shell(`${top()}<div class="row between"><div><div class="tiny">CREW CHAT</div><h1>Chat</h1></div></div><div class="sp12"></div><div id="chat" class="chat">${chatHtml(j.messages)}</div><div class="composer"><input id="chatInput" maxlength="240" placeholder="Message your Crew…" onkeydown="if(event.key==='Enter')window._sendChat()"><button onclick="window._sendChat()">Send</button></div><div class="quick"><button onclick="window._quick('😂')">😂</button><button onclick="window._quick('😭')">😭</button><button onclick="window._quick('🔥')">🔥</button><button onclick="window._quick('👀')">👀</button></div>`);const box=$('#chat');if(box)box.scrollTop=box.scrollHeight;chatTimer=setInterval(()=>{if(screen==='crew'&&tab==='chat')refreshChatMessages()},3000)}
window._quick=x=>{const i=$('#chatInput');if(!i)return;i.value=(i.value+' '+x).trim();i.focus()};window._sendChat=async()=>{const i=$('#chatInput');const text=i?.value.trim();if(!text)return;try{await api('chatSend',{method:'POST',body:{crewId,participantId:pid,text}});track('chat_message_sent');i.value='';await refreshChatMessages();i.focus()}catch(e){toast(e.message)}};

boot();
